version: '3.7'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: itau_coding_challenge
    container_name: database-itau-docker
  
  plataform:
    build:
      context: ./apps/plataform
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./apps/plataform:/home/apps/plataform
    container_name: plataform-docker
    depends_on:
      - 'auth'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: bash -c "npm install -D prisma@4.0.0 && npx prisma migrate dev && npm run dev"

  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./apps/auth:/home/apps/auth
    container_name: auth-docker    
    depends_on:
      - 'database'
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: bash -c "npm install -D prisma@4.0.0 && npx prisma migrate dev && npm run dev"