export { default as Movie } from './movie'
export { default as Comment } from './comment'
export { default as Rating } from './rating'
export { default as CommentReview } from './commentReview'
export { default as User } from './user'